# Generated by Django 6.0.3 on 2026-04-08 04:25

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier for the organisation.', unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='Current subscription plan.', max_length=20)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('meetings_this_month', models.IntegerField(default=0)),
                ('usage_reset_date', models.DateField(blank=True, help_text='Date when monthly usage counters were last reset.', null=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, help_text='Must be set when organisation is set. Must be null when organisation is null.', max_length=20, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('email_notifications', models.BooleanField(default=True)),
                ('meeting_reminders', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, help_text='Null = individual user. Set = organisation member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw key. Never store the raw key.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Human readable label e.g. "Production Bot Key".', max_length=100)),
                ('prefix', models.CharField(help_text='First 8 chars of the raw key shown in UI e.g. "re_live_".', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Updated every time this key is used to authenticate.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null means the key never expires.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address of the person being invited.', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Role the invited user will receive on joining.', max_length=20)),
                ('code', models.CharField(default=secrets.token_urlsafe, help_text='URL-safe token sent to the invitee. Never expose in list endpoints.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Invite automatically becomes invalid after this time.')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Invite',
                'verbose_name_plural': 'Organisation Invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organisation', 'is_active'], name='user_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organisation', 'org_role'], name='user_org_role_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationinvite',
            index=models.Index(fields=['organisation', 'status'], name='invite_org_status_idx'),
        ),
    ]
