# Generated by Django 6.0.3 on 2026-04-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, help_text='Hashed or plain numeric code for password resets/verification.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, help_text='Timestamp after which the current OTP becomes invalid.', null=True),
        ),
    ]
