"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Logs Directory
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Load .env file (check backend/ or root/)
dotenv_path = os.path.join(BASE_DIR, '.env')
if not os.path.exists(dotenv_path):
    dotenv_path = os.path.join(BASE_DIR.parent, '.env')
load_dotenv(dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '0.0.0.0']

# Since we are using Nginx as a proxy, add this:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',

    'accounts',
    'meetings',
    'transcripts',
    'rag',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "utils.middleware.RequestLoggingMiddleware",
    "utils.middleware.TenantMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Recommended for production
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model — must be set or Django uses its built-in auth.User
AUTH_USER_MODEL = 'accounts.User'

#-------------------Rest Framework & Spectacular Settings ------------------

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',
        'user': '1000/min',
        'auth': '5/min',
    },
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',
    'EXCEPTION_HANDLER': 'utils.exception_handler.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Audicle API',
    'DESCRIPTION': 'API documentation for Audicle backend',
    'VERSION': '1.0.0',
}

# ------------------ JWT Authentication Settings ------------------

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,      # Security: Issue a new refresh token on every refresh
    'BLACKLIST_AFTER_ROTATION': True,   # Security: Old refresh tokens are invalidated immediately
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

#------------------- CORS & CSRF Settings ------------------

# Required for the browser to allow HttpOnly cookies in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

# List of frontend URLs allowed to access this API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Add your production frontend URL here
]

# CSRF protection: Ensure cookies are sent safely
CSRF_COOKIE_HTTPONLY = False  # Set to True only if not using JS to read CSRF token
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Google OAuth Client ID
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# ------------------ LOGGING CONFIGURATION ------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django_errors.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'meetings': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'utils': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'transcripts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ------------------ Celery Configuration ------------------

# Broker: Redis DB 0
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

# Result backend: Redis DB 2
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/2')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Store task results in Django DB via django-celery-results
CELERY_RESULT_BACKEND = 'django-db'

# Celery Beat — Periodic Task Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Runs every hour — nulls out otp/otp_expiry on expired records
    'cleanup-expired-otps-every-hour': {
        'task': 'accounts.tasks.cleanup_expired_otps_task',
        'schedule': crontab(minute=0),  # top of every hour
    },
    # Runs at midnight on the 1st of every month
    'reset-monthly-usage-first-of-month': {
        'task': 'accounts.tasks.reset_monthly_usage_task',
        'schedule': crontab(hour=0, minute=0, day_of_month=1),
    },
    # Runs every 5 minutes — auto-dispatches bots for upcoming meetings
    'auto-dispatch-bots-every-5-minutes': {
        'task': 'meetings.auto_dispatch_bots',
        'schedule': crontab(minute='*/5'),
    },
}


# ------------- AWS S3 -----------------------
AWS_ACCESS_KEY_ID        = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY    = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME  = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION            = os.environ.get("AWS_S3_REGION", "ap-southeast-2")

AWS_PRESIGNED_UPLOAD_EXPIRY   = 900
AWS_PRESIGNED_DOWNLOAD_EXPIRY = 3600

AWS_ALLOWED_UPLOAD_TYPES = {
    "audio/mpeg":       "mp3",
    "audio/mp3":        "mp3",
    "audio/x-mp3":      "mp3",
    "audio/mp4":        "mp4",
    "audio/wav":        "wav",
    "audio/x-wav":      "wav",
    "audio/wave":       "wav",
    "audio/vnd.wav":    "wav",
    "audio/m4a":        "m4a",
    "audio/x-m4a":      "m4a",
    "audio/webm":       "webm",
    "audio/ogg":        "ogg",
    "audio/opus":       "opus",
    "video/mp4":        "mp4",
    "video/webm":       "webm",
    "video/quicktime":  "mov",
    "video/x-matroska": "mkv",
}

AWS_MAX_UPLOAD_SIZE = 500 * 1024 * 1024

# -------------Internal microservice communication-----------------
INTERNAL_API_SECRET = os.environ.get("INTERNAL_API_SECRET", "change-me-in-production")

# ------------- AI Backend Configuration -----------------
AI_BACKEND = os.environ.get("AI_BACKEND", "gemini")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_MODEL   = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
OPENAI_MODEL   = os.environ.get("OPENAI_MODEL", "gpt-4o")

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://ollama:11434/v1")
OLLAMA_MODEL    = os.environ.get("OLLAMA_MODEL", "llama3.2")

SUMMARY_MAX_TOKENS    = 4000
SUMMARY_CHUNK_OVERLAP = 100

# Channel layer (Redis db=2 to keep separate from broker/cache)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get("REDIS_HOST", "redis"), 6379)],
            "capacity": 1500,
            "expiry": 60,
        },
    }
}