# Generated by Django 6.0.3 on 2026-05-10 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_customer_id', models.CharField(help_text='Razorpay customer ID e.g. cust_XXXXXXXXXX', max_length=255, unique=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, help_text='Razorpay subscription ID e.g. sub_XXXXXXXXXX', max_length=255, null=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_status', models.CharField(blank=True, help_text='created/authenticated/active/paused/cancelled/expired', max_length=50, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_customers', to='accounts.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Razorpay Customer',
                'verbose_name_plural': 'Razorpay Customers',
                'indexes': [models.Index(fields=['user', 'plan'], name='billing_raz_user_id_ecb601_idx'), models.Index(fields=['razorpay_subscription_id'], name='billing_raz_razorpa_00987c_idx')],
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
