# Generated by Django 6.0.3 on 2026-05-13 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_create_razorpay_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('razorpay_plan_id', models.CharField(blank=True, help_text='Razorpay plan ID e.g. plan_XXXXXXXXXX. Leave blank for Free plan.', max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meeting_limit', models.IntegerField(default=5, help_text='Number of meetings allowed per month. Use -1 for unlimited.')),
                ('max_workspaces', models.IntegerField(default=2, help_text='For Personal plan users.')),
                ('max_members', models.IntegerField(default=3, help_text='For Organisation plans.')),
                ('bot_access', models.BooleanField(default=True)),
                ('rag_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_subscription_id', models.CharField(blank=True, help_text='Razorpay subscription ID e.g. sub_XXXXXXXXXX', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='razorpaycustomer',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='razorpaycustomer',
            name='billing_raz_user_id_ecb601_idx',
        ),
        migrations.RemoveIndex(
            model_name='razorpaycustomer',
            name='billing_raz_razorpa_00987c_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RazorpayCustomer',
        ),
    ]
