[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --cov=. --cov-report=html --cov-report=term-missing
filterwarnings =
    ignore::DeprecationWarning:botocore.*
    ignore::DeprecationWarning:razorpay.*
    ignore::DeprecationWarning:pkg_resources.*
    ignore::DeprecationWarning:daphne.*
