# Generated by Django 6.0.3 on 2026-05-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
