# Generated by Django 6.0.3 on 2026-05-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingparticipant',
            options={'ordering': ['joined_at', 'id'], 'verbose_name': 'Meeting Participant', 'verbose_name_plural': 'Meeting Participants'},
        ),
    ]
