# Generated by Django 6.0.3 on 2026-05-05 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meetings', '0002_alter_meetingparticipant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('default_participants', models.JSONField(blank=True, default=list)),
                ('summary_format', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_templates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_templates', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organisation'], name='meetings_me_organis_015737_idx'), models.Index(fields=['created_by'], name='meetings_me_created_c065c4_idx')],
            },
        ),
    ]
