# Generated by Django 6.0.3 on 2026-05-07 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meetings', '0003_meetingtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID — used to prevent duplicate imports', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['google_event_id'], name='meetings_me_google__6a82ee_idx'),
        ),
    ]
