# Generated by Django 6.0.3 on 2026-05-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_add_google_event_id_to_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recall_bot_id',
            field=models.CharField(blank=True, help_text='Recall.ai bot ID for tracking', max_length=255, null=True),
        ),
    ]
