# Generated by Django 6.0.3 on 2026-04-24 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_mfa_enabled_user_mfa_secret'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('language', models.CharField(default='en', help_text='Language detected by Whisper e.g. en, hi, fr', max_length=10)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Full transcript text joined from all segments')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Auto-computed from raw_text on save')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total audio duration reported by Whisper', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of transcription attempts')),
                ('error_message', models.TextField(blank=True, help_text='Stores failure reason if status=failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='meetings.meeting')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_label', models.CharField(blank=True, help_text='Speaker label e.g. SPEAKER_01 — filled in Phase 7', max_length=50, null=True)),
                ('text', models.TextField(help_text='Transcript text for this segment')),
                ('start_seconds', models.FloatField(help_text='Segment start time in seconds')),
                ('end_seconds', models.FloatField(help_text='Segment end time in seconds')),
                ('confidence', models.FloatField(blank=True, help_text='Whisper confidence score 0.0 to 1.0', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcripts.transcript')),
            ],
            options={
                'verbose_name': 'Transcript Segment',
                'verbose_name_plural': 'Transcript Segments',
                'ordering': ['start_seconds'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['meeting'], name='transcripts_meeting_852ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['organisation', 'status'], name='transcripts_organis_72a66d_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['created_by', 'status'], name='transcripts_created_01d7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcript', 'start_seconds'], name='transcripts_transcr_de1721_idx'),
        ),
    ]
