# Generated by Django 6.0.3 on 2026-04-25 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mfa_enabled_user_mfa_secret'),
        ('meetings', '0001_initial'),
        ('transcripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True, default='', help_text='3-5 sentence overview of the meeting')),
                ('key_points', models.JSONField(default=list, help_text='List of key discussion points')),
                ('action_items', models.JSONField(default=list, help_text='List of action items with owner and due date')),
                ('decisions', models.JSONField(default=list, help_text='List of decisions made in the meeting')),
                ('next_steps', models.JSONField(default=list, help_text='List of next steps')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meeting')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Meeting Summary',
                'verbose_name_plural': 'Meeting Summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['meeting'], name='transcripts_meeting_6fadda_idx'), models.Index(fields=['organisation', 'status'], name='transcripts_organis_e63d2f_idx')],
            },
        ),
    ]
