# Generated by Django 6.0.3 on 2026-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptsegment',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='True if this segment was manually edited by a user'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='speaker_name',
            field=models.CharField(blank=True, help_text='Human-readable speaker name — set manually by user', max_length=255, null=True),
        ),
    ]
