# Generated by Django 6.0.3 on 2026-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_add_speaker_name_is_edited_to_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsummary',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Stores translated versions of the summary: { 'Hindi': { 'summary': '...', ... } }"),
        ),
    ]
