from rest_framework import serializers

from transcripts.models import Transcript, TranscriptSegment, MeetingSummary


class TranscriptSegmentSerializer(serializers.ModelSerializer):
    duration_seconds = serializers.FloatField(read_only=True)

    class Meta:
        model = TranscriptSegment
        fields = [
            "id",
            "speaker_label",
            "text",
            "start_seconds",
            "end_seconds",
            "confidence",
            "duration_seconds",
            "created_at",
        ]
        read_only_fields = ["id", "duration_seconds", "created_at"]


class TranscriptSerializer(serializers.ModelSerializer):
    segments = TranscriptSegmentSerializer(many=True, read_only=True)
    meeting_id = serializers.UUIDField(source="meeting.id", read_only=True)
    meeting_title = serializers.CharField(
        source="meeting.title", read_only=True)

    class Meta:
        model = Transcript
        fields = [
            "id",
            "meeting_id",
            "meeting_title",
            "status",
            "language",
            "raw_text",
            "word_count",
            "duration_seconds",
            "retry_count",
            "error_message",
            "is_completed",
            "can_retry",
            "segments",
            "created_at",
            "updated_at",
        ]
        read_only_fields = [
            "id", "meeting_id", "meeting_title",
            "status", "language", "raw_text",
            "word_count", "duration_seconds",
            "retry_count", "error_message",
            "is_completed", "can_retry",
            "created_at", "updated_at",
        ]


class TranscriptSegmentListSerializer(serializers.ModelSerializer):
    """
    Lightweight serializer for segment list endpoint.
    Excludes nested data for performance.
    """
    duration_seconds = serializers.FloatField(read_only=True)

    class Meta:
        model = TranscriptSegment
        fields = [
            "id",
            "speaker_label",
            "text",
            "start_seconds",
            "end_seconds",
            "confidence",
            "duration_seconds",
        ]


# ----------------- Internal serializers (not exposed via public API) -----------------

class InternalSegmentSerializer(serializers.Serializer):
    """
    Validates a single segment from Whisper worker.
    """
    text = serializers.CharField()
    start_seconds = serializers.FloatField()
    end_seconds = serializers.FloatField()
    confidence = serializers.FloatField(required=False, allow_null=True)


class InternalTranscriptCompleteSerializer(serializers.Serializer):
    """
    Validates the payload sent by ai_worker after transcription.

    Called by:
        POST /api/v1/internal/transcript/complete/
        Header: X-Internal-Secret: <secret>

    Sent by:
        ai_service/worker.py after Whisper finishes
    """
    meeting_id = serializers.UUIDField()
    status = serializers.ChoiceField(
        choices=["completed", "failed"]
    )
    language = serializers.CharField(
        max_length=10,
        default="en",
        required=False,
    )
    raw_text = serializers.CharField(
        allow_blank=True,
        default="",
        required=False,
    )
    duration_seconds = serializers.FloatField(
        required=False,
        allow_null=True,
    )
    segments = InternalSegmentSerializer(
        many=True,
        required=False,
        default=list,
    )
    error_message = serializers.CharField(
        required=False,
        allow_null=True,
        allow_blank=True,
    )


# --------------Meeting summary serializers-----------------

class MeetingSummarySerializer(serializers.ModelSerializer):
    """
    Serializer for reading meeting summary data.
    All fields are read only — summary is generated by AI not user input.
    """
    meeting_id = serializers.UUIDField(
        source="meeting.id",
        read_only=True,
    )
    meeting_title = serializers.CharField(
        source="meeting.title",
        read_only=True,
    )
    can_retry = serializers.BooleanField(read_only=True)

    class Meta:
        model = MeetingSummary
        fields = [
            "id",
            "meeting_id",
            "meeting_title",
            "status",
            "summary",
            "key_points",
            "action_items",
            "decisions",
            "next_steps",
            "retry_count",
            "error_message",
            "can_retry",
            "created_at",
            "updated_at",
        ]
        read_only_fields = [
            "id",
            "meeting_id",
            "meeting_title",
            "status",
            "summary",
            "key_points",
            "action_items",
            "decisions",
            "next_steps",
            "retry_count",
            "error_message",
            "can_retry",
            "created_at",
            "updated_at",
        ]


class TranslateSummarySerializer(serializers.Serializer):
    """
    Validates translation request.
    User provides target language as a plain string.

    Example:
    {"target_language": "Malayalam"}
    {"target_language": "Hindi"}
    {"target_language": "French"}
    """
    target_language = serializers.CharField(
        max_length=50,
        help_text="Language name e.g. Malayalam, Hindi, French, Arabic",
    )

    def validate_target_language(self, value):
        """
        Clean and normalize the language name.
        'malayalam' → 'Malayalam'
        ' hindi '   → 'Hindi'
        """
        cleaned = value.strip().title()
        if not cleaned:
            raise serializers.ValidationError(
                "Target language cannot be empty."
            )
        return cleaned


class InternalSummaryCompleteSerializer(serializers.Serializer):
    """
    Validates the payload sent by ai_worker after GPT-4o/Gemini finishes.

    Called by:
        POST /api/v1/internal/summary/complete/
        Header: X-Internal-Secret: <secret>

    Sent by:
        ai_service/worker.py after summarization finishes
    """
    meeting_id = serializers.UUIDField()
    status = serializers.ChoiceField(
        choices=["completed", "failed"]
    )
    summary = serializers.CharField(
        allow_blank=True,
        required=False,
        default="",
    )
    key_points = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        default=list,
    )
    action_items = serializers.ListField(
        child=serializers.DictField(),
        required=False,
        default=list,
    )
    decisions = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        default=list,
    )
    next_steps = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        default=list,
    )
    error_message = serializers.CharField(
        required=False,
        allow_null=True,
        allow_blank=True,
    )


class TranscriptSegmentEditSerializer(serializers.ModelSerializer):
    """Used for PATCH — only text and speaker_name are editable."""

    class Meta:
        model = TranscriptSegment
        fields = [
            "id",
            "speaker_label",
            "speaker_name",
            "text",
            "start_seconds",
            "end_seconds",
            "confidence",
            "is_edited",
            "created_at",
        ]
        read_only_fields = [
            "id",
            "speaker_label",
            "start_seconds",
            "end_seconds",
            "confidence",
            "is_edited",
            "created_at",
        ]

    def validate_text(self, value):
        value = value.strip()
        if not value:
            raise serializers.ValidationError("Segment text cannot be empty.")
        return value

