# Generated by Django 6.0.3 on 2026-05-07 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='Google OAuth access token')),
                ('refresh_token', models.TextField(help_text='Google OAuth refresh token — used to get new access tokens')),
                ('token_expiry', models.DateTimeField(help_text='When the access token expires')),
                ('google_email', models.EmailField(help_text='Google account email this token belongs to', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='False if user disconnected or token was revoked')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time we successfully fetched events from Google', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message if any', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tokens', to='accounts.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='calendar_in_user_id_0aa493_idx'), models.Index(fields=['organisation', 'is_active'], name='calendar_in_organis_244e35_idx')],
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
