# Generated by Django 6.0.3 on 2026-04-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_initial'),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingchunk',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='transcripts.transcript'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='rag_chatses_user_id_4c6d02_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['organisation'], name='rag_chatses_organis_0a4490_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session'], name='rag_chatmes_session_f9d623_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['transcript'], name='rag_embeddi_transcr_d88672_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['meeting'], name='rag_embeddi_meeting_31111b_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['organisation'], name='rag_embeddi_organis_6d608d_idx'),
        ),
    ]
